### ISSUE TITLE
Plugin 1 specified in "base.env.production" provided an invalid property of "default"

### ISSUE THREAD

**Issue by LiaoSept** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#10]
```javascript
require("babel-core").transform("code", {
  plugins: [require('babel-plugin-transform-react-remove-prop-types')]
});
```

error info:
```
Error: Plugin 1 specified in "base.env.production" provided an invalid property of "default" while parsing file: /home/development/Projects/project/js/main.js
    at Plugin.init (/home/development/Projects/project/node_modules/babel-core/lib/transformation/plugin.js:115:13)
    at Function.normalisePlugin (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:149:12)
    at /home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:183:30
    at Array.map (native)
    at Function.normalisePlugins (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:155:20)
    at OptionManager.mergeOptions (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:277:36)
    at OptionManager.mergeOptions (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:330:10)
    at OptionManager.init (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/options/option-manager.js:465:10)
    at File.initOptions (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/index.js:194:75)
    at new File (/home/development/Projects/project/node_modules/babel-core/lib/transformation/file/index.js:123:22)

```

**Comment by oliviertassinari** [comment]
Can you try?
```js
require("babel-core").transform("code", {
  plugins: [require('babel-plugin-transform-react-remove-prop-types').default]
});
```

**Comment by LiaoSept** [comment]
ok pass
