### ISSUE TITLE
Babel configuration doesn't accept plugin with options - path must be a string

### ISSUE THREAD

**Issue by rosskevin** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#116]
The following fails once I try to add an option to `babel-plugin-flow-react-proptypes`:
```
    ["transform-react-remove-prop-types", {
          "mode": "wrap",
          "plugins": [
            ["babel-plugin-flow-react-proptypes", {"omitRuntimeTypeExport": true}],
            "babel-plugin-transform-flow-strip-types"
          ]
        }]
```

```
AssertionError [ERR_ASSERTION]: path must be a string
    at Module.require (module.js:512:3)
    at require (internal/module.js:11:18)
    at /Users/kross/projects/material-ui/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:35:26
    at Array.map (native)
    at PluginPass.Program (/Users/kross/projects/material-ui/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:34:52)
    at newFn (/Users/kross/projects/material-ui/node_modules/babel-traverse/lib/visitors.js:276:21)
    at NodePath._call (/Users/kross/projects/material-ui/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/kross/projects/material-ui/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/kross/projects/material-ui/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/kross/projects/material-ui/node_modules/babel-traverse/lib/context.js:150:16)
```

**Comment by oliviertassinari** [comment]
Ah right: https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/blob/67f9d62b0a996cc5a23ff75d0bb114ba7cc73eb6/src/index.js#L81.
I can fix that.

**Comment by rosskevin** [comment]
@oliviertassinari - [still have the problem](https://circleci.com/gh/callemall/material-ui/5059?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), cannot `yarn build` material-ui after updating the plugin.

You can try my branch if that helps https://github.com/callemall/material-ui/pull/7609

**Comment by oliviertassinari** [comment]
Oh no! Let me look into it, could be an issue with the publish.

**Comment by oliviertassinari** [comment]
I confirm, I have messed-up the release 🙈 .
