### ISSUE TITLE
Babel error with mode: "remove"

### ISSUE THREAD

**Issue by bvaughn** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#60]
I recently tried integrating this plugin with react-virtualized. (I prefer declaring `propTypes` inside of the class body rather than at the footer so I was excited about the "wrap" mode.)

Running with `mode: "remove"` (the default) worked fine for me but when I tried running with `mode: "wrap"` I got [the following error](https://circleci.com/gh/bvaughn/react-virtualized/1121):

```
Error: source/ArrowKeyStepper/ArrowKeyStepper.js: We don't know what to do with this node type. We were previously a Statement but we can't fit in here?
    at NodePath.insertAfter (../node_modules/babel-core/node_modules/babel-traverse/lib/path/modification.js:175:13)
    at remove (../node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:185:30)
    at ClassProperty (../node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:58:17)
    at NodePath._call (../node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (../node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (../node_modules/babel-core/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (../node_modules/babel-core/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (../node_modules/babel-core/node_modules/babel-traverse/lib/context.js:103:17)
    at TraversalContext.visit (../node_modules/babel-core/node_modules/babel-traverse/lib/context.js:190:19)
    at Function.traverse.node (../node_modules/babel-core/node_modules/babel-traverse/lib/index.js:114:17)
```

FWIW, the `container` in question is of `type: "ExportDefaultDeclaration"` and the `node` is of `type: "ClassDeclaration"`.

For what it's worth, I tried patching the change from your PR #45 onto my local version of babel-plugin-transform-react-remove-prop-types but it didn't seem to resolve the issue.

You can reproduce this issue (if you're interested) by checking out [the `propTypes` branch of react-virtualized](https://github.com/bvaughn/react-virtualized/tree/propTypes) and then running:

```
npm i
npm run build
```

**Comment by oliviertassinari** [comment]
The issue seems to be fixed. I have used the following command on your branch without any issue:
> 01:30:52 (propTypes) ~/react-virtualized$ npm run build:commonjs

The `dist/commonjs/ArrowKeyStepper/ArrowKeyStepper.js` file looks fine:
```js

  return ArrowKeyStepper;
}(_react.Component);

exports.default = ArrowKeyStepper;
process.env.NODE_ENV !== "production" ? ArrowKeyStepper.propTypes = {
  children: _react.PropTypes.func.isRequired,
  className: _react.PropTypes.string,
  columnCount: _react.PropTypes.number.isRequired,
  rowCount: _react.PropTypes.number.isRequired
} : void 0;
```

**Comment by bvaughn** [comment]
Gah, sorry it's taken me 2 days to get back to you to verify the fix. Onboarding at Facebook this week has been pretty distracting.

Just installed 0.2.10 and I can confirm that I'm able to run `npm build` without any problems now. 🙇 Thanks a bunch! 😁

**Comment by oliviertassinari** [comment]
🎉
