### ISSUE TITLE
Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null

### ISSUE THREAD

**Issue by mbrevda** [oliviertassinari/babel-plugin-transform-react-remove-prop-types#76]
When trying to run with webpack 2.2.1, I'm getting the following error:

```
ERROR in ./~/react-intl/lib/index.es.js
Module build failed: TypeError: [redacted]/node_modules/react-intl/lib/index.es.js: Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null
```

<details>

    Module build failed: TypeError: [redacted]/node_modules/react-intl/lib/index.es.js: Property consequent of ConditionalExpression expected node to be of a type ["Expression"] but instead got null
        at Object.validate ([redacted]/node_modules/babel-types/lib/definitions/index.js:109:13)
        at Object.validate ([redacted]/node_modules/babel-types/lib/index.js:511:9)
        at NodePath._replaceWith ([redacted]/node_modules/babel-traverse/lib/path/replacement.js:176:7)
        at NodePath._remove ([redacted]/node_modules/babel-traverse/lib/path/removal.js:58:10)
        at NodePath.remove ([redacted]/node_modules/babel-traverse/lib/path/removal.js:30:8)
        at remove ([redacted]/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:157:10)
        at AssignmentExpression ([redacted]/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:97:15)
        at NodePath._call ([redacted]/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call ([redacted]/node_modules/babel-traverse/lib/path/context.js:48:17)
        at NodePath.visit ([redacted]/node_modules/babel-traverse/lib/path/context.js:105:12)
        at TraversalContext.visitQueue ([redacted]/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle ([redacted]/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit ([redacted]/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node ([redacted]/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit ([redacted]/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue ([redacted]/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitSingle ([redacted]/node_modules/babel-traverse/lib/context.js:108:19)
        at TraversalContext.visit ([redacted]/node_modules/babel-traverse/lib/context.js:192:19)
        at Function.traverse.node ([redacted]/node_modules/babel-traverse/lib/index.js:114:17)
        at NodePath.visit ([redacted]/node_modules/babel-traverse/lib/path/context.js:115:19)
        at TraversalContext.visitQueue ([redacted]/node_modules/babel-traverse/lib/context.js:150:16)
        at TraversalContext.visitMultiple ([redacted]/node_modules/babel-traverse/lib/context.js:103:17)
        at TraversalContext.visit ([redacted]/node_modules/babel-traverse/lib/context.js:190:19)
        at Function.traverse.node ([redacted]/node_modules/babel-traverse/lib/index.js:114:17)
        at traverse ([redacted]/node_modules/babel-traverse/lib/index.js:79:12)
        at NodePath.traverse ([redacted]/node_modules/babel-traverse/lib/path/index.js:144:25)
        at PluginPass.Program ([redacted]/node_modules/babel-plugin-transform-react-remove-prop-types/lib/index.js:21:21)
        at newFn ([redacted]/node_modules/babel-traverse/lib/visitors.js:276:21)
        at NodePath._call ([redacted]/node_modules/babel-traverse/lib/path/context.js:76:18)
        at NodePath.call ([redacted]/node_modules/babel-traverse/lib/path/context.js:48:17)
     @ ./src/containers/MatchCenterScores.js 31:17-38
     @ ./src/containers/index.js
     @ ./src/app.js
</details>

Here is my .babelrc:
<details>

    {
        "presets": ["es2015", "react"],
        "plugins": [
            ["transform-object-rest-spread", {useBuiltIns: true}],
            "transform-es2015-destructuring",
            "transform-class-properties",
            "transform-export-extensions",
            "lodash",
            "react-intl",
            "transform-node-env-inline",
            //"transform-inline-environment-variables",
            "transform-react-remove-prop-types"
        ]
    }

</details>

Here is my webpack config:

<details>
    var path = require('path')

    module.exports = {
        entry: './src/app.js',
        output: {
            filename: 'bundle.js',
            path: path.resolve(__dirname, 'build')
        },
        module: {
            rules: [
                {test: /\.(js|jsx)$/, use: 'babel-loader'}
            ]
        },
        resolve: {
            modules: [path.resolve(__dirname, 'src'), 'node_modules']
        }
    }

</details>

**Comment by oliviertassinari** [comment]
Thanks, here is a minimal reproduction test case:
```jsx
const FormattedPlural = () => <div />;

process.env.NODE_ENV !== 'production' ? FormattedPlural.propTypes = {
  value: PropTypes.any.isRequired,
} : void 0;
```

**Comment by mbrevda** [comment]
Thanks!
